baseurl = "https://www.example.org/"
title = "Kiera"
copyright = "Copyright &copy; 2019 - Author Name"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Example"
    github = "funkydan2"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "ds_says"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname

[params]
    tagline = "A Hugo theme for creative and technical writing"
    description = "Kiera: A Hugo theme for creative and technical writing."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "https://github.com/MyRepo"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1
